(Role Antero (pitch 0.5))
(Antero heippa!)
(Antero Moi vaan (SOUND AnteronMoi))
(Wait tauko (length 300))
(tauko) 
(* kommentti *)
(sound pam (SOUND pam.mp3))
(pam)
(Role Tiina)
(Group Me (members Antero Tiina pam))
(Me Hei hei)